### ISSUE TITLE
1.19.x+ Paper/Spigot Implementation

### ISSUE THREAD

**Issue by TraipsingShadow** [haruww/simple-radio#7]
Hello! I stumbled upon this add-on only via the Discord server as it is not part of the "official" list found on Modrinth.

This add-on was more or less the thing I was looking for! Alas, it is on 1.16.5 only and requires an item.

I run a tiny private Paper/Spigot server and was on the lookout for such a feature that could be compatible.

I honestly don't know if my suggestion can garner enough attention to encourage the developers of this add-on as it seems to be a niche use-case. Regardless, let me present my idea for a plugin version of this add-on.

<hr>
<h3>The Details</h3>

<details>
<summary><h4>1. The Radio/Walkie-talkie</h4></summary>
<p>From my understanding, this add-on adds in a physical radio item. There are two "Vanilla"-friendly ways of executing this (one being renaming an item and it becomes a radio) but I am opting for the simplest way to do it. My suggestion is the plugin version forgoes the item entirely and just have everything accessible via commands. I don't know about programming but that should help reduce the complexity of it... right?</p>

<p>Staying true to its name, it will truly be a simple radio!</p>
</details>

<details>
<summary><h4>2. The Frequency System</h4></summary>
<p>Okay, perhaps this part is not so simple, but would it be possible to group users into "frequencies" or groups? Being aware of the limitations in Vanilla, the user would have to input a command to enter a frequency (which is essentially a group room). As soon as the user is inside a frequency, he can no longer use Push-to-talk (PTT) to talk to people near him as the PTT is now bound to the frequency. Hitting the PTT bound key will instead mute them for the surrounding people and transmit his voice only through the frequency.</p>

<p>In essence, the same as this add-on, but without needing the complexity of a GUI (I am trying to think of the simplest way to do this without adding complex stuff).</p>

<p>Think "Staff" frequencies or "Moderator" frequencies. I don't have such need for groups, but I feel like it would make this add-on and the mod/plugin it builds off of be a lot more attractive.</p>
</details>
<hr>

I hope these suggestions find their home somewhere!

**Comment by 301haru** [comment]
Fisrt, I'm not gonna make a plugin version of this mod becasue I don't agree Commands are more intuitive, user friendly than GUI system. It sounds like you're saying Linux command line is easier than Windows..
I also considered making a plugin version, but I discarded it for this reason.

Second, the frequency system that you suggest seems little bit impossible to make as far as I correctly understand, because there's no way to know if user pushed the PTT key because that is client sided. Also thats kind of a reason why there's two seperated PTT key on this mod.
But I'm pretty sure there's some way by using Simple Voice "Group" function 

I hope someone can make your ideas come true, but unfortunately there's not much here to help you.
